// AUTO-GENERATED by scripts/gen-brand-assets.mjs - do not edit.
import type { SVGProps } from "react";

/**
 * The dosya mark, inline. Ink is currentColor so it follows the lockup's text
 * colour; the seal is the brand green in both themes. Size it with a className
 * (`h-7 w-7`). Decorative by default: pass `aria-label` when it stands alone.
 */
export function Logo({ className, ...props }: SVGProps<SVGSVGElement>) {
  const labelled = props["aria-label"] != null;
  return (
    <svg
      viewBox="0 0 24 24"
      className={className}
      aria-hidden={labelled ? undefined : true}
      role={labelled ? "img" : undefined}
      {...props}
    >
      <path
        d="M3 7.5A2.5 2.5 0 0 1 5.5 5h4.2l2.1 2.6h6.7A2.5 2.5 0 0 1 21 10.1v7.4A2.5 2.5 0 0 1 18.5 20h-13A2.5 2.5 0 0 1 3 17.5z"
        fill="none"
        stroke="currentColor"
        strokeWidth="2.2"
        strokeLinejoin="round"
      />
      <circle cx="16.6" cy="14.6" r="2.1" className="fill-[#16a34a] dark:fill-[#22c55e]" />
    </svg>
  );
}
