// AUTO-GENERATED by packages/brand/src/generate.mjs - do not edit.
//
// Data colours: the hues that carry information rather than brand. See
// packages/brand/src/palette.mjs for why `chart` and `swatches` are separate sets and
// why `chart` stops at five.

export type SwatchName = "green" | "teal" | "blue" | "violet" | "pink" | "orange" | "graphite";

export interface Swatch {
  name: SwatchName;
  label: string;
  /** Fill for a light surface, and the label colour that meets AA on it. */
  light: string;
  lightInk: string;
  /** Fill for a dark surface. Bright, so the label is near-black, not the theme ink. */
  dark: string;
  darkInk: string;
}

/** Series colours, verified distinguishable under simulated colour-vision deficiency. */
export const CHART: { light: string[]; dark: string[] } = {
  "light": [
    "#15803d",
    "#1e40af",
    "#d97706",
    "#7e22ce",
    "#475569"
  ],
  "dark": [
    "#4ade80",
    "#3b82f6",
    "#fcd34d",
    "#c084fc",
    "#94a3b8"
  ]
};

/** Identity colours for workspaces, folder groups and avatars. */
export const SWATCHES: Swatch[] = [
  {
    "name": "green",
    "label": "Green",
    "light": "#15803d",
    "dark": "#4ade80",
    "lightInk": "#ffffff",
    "darkInk": "#181818"
  },
  {
    "name": "teal",
    "label": "Teal",
    "light": "#0f766e",
    "dark": "#2dd4bf",
    "lightInk": "#ffffff",
    "darkInk": "#181818"
  },
  {
    "name": "blue",
    "label": "Blue",
    "light": "#1d4ed8",
    "dark": "#60a5fa",
    "lightInk": "#ffffff",
    "darkInk": "#181818"
  },
  {
    "name": "violet",
    "label": "Violet",
    "light": "#6d28d9",
    "dark": "#c084fc",
    "lightInk": "#ffffff",
    "darkInk": "#181818"
  },
  {
    "name": "pink",
    "label": "Pink",
    "light": "#be185d",
    "dark": "#f472b6",
    "lightInk": "#ffffff",
    "darkInk": "#181818"
  },
  {
    "name": "orange",
    "label": "Orange",
    "light": "#c2410c",
    "dark": "#fb923c",
    "lightInk": "#ffffff",
    "darkInk": "#181818"
  },
  {
    "name": "graphite",
    "label": "Graphite",
    "light": "#3f3f46",
    "dark": "#a1a1aa",
    "lightInk": "#ffffff",
    "darkInk": "#181818"
  }
];

export const SWATCH_BY_NAME: Record<SwatchName, Swatch> = Object.fromEntries(
  SWATCHES.map((s) => [s.name, s]),
) as Record<SwatchName, Swatch>;

/** File family to swatch name. */
export const FILE_FAMILY: Record<string, SwatchName> = {
  "folder": "teal",
  "image": "violet",
  "video": "pink",
  "audio": "orange",
  "document": "blue",
  "spreadsheet": "green",
  "presentation": "orange",
  "pdf": "blue",
  "archive": "orange",
  "code": "violet",
  "ebook": "violet",
  "text": "graphite",
  "other": "graphite"
};

/** Extension to family, so an extension and a family never disagree. */
export const EXTENSION_FAMILY: Record<string, string> = {
  "pdf": "pdf",
  "doc": "document",
  "docx": "document",
  "odt": "document",
  "rtf": "document",
  "xls": "spreadsheet",
  "xlsx": "spreadsheet",
  "ods": "spreadsheet",
  "csv": "spreadsheet",
  "ppt": "presentation",
  "pptx": "presentation",
  "odp": "presentation",
  "png": "image",
  "jpg": "image",
  "jpeg": "image",
  "gif": "image",
  "svg": "image",
  "webp": "image",
  "heic": "image",
  "heif": "image",
  "avif": "image",
  "bmp": "image",
  "mp4": "video",
  "mov": "video",
  "avi": "video",
  "mkv": "video",
  "webm": "video",
  "mp3": "audio",
  "wav": "audio",
  "flac": "audio",
  "aac": "audio",
  "ogg": "audio",
  "m4a": "audio",
  "zip": "archive",
  "rar": "archive",
  "7z": "archive",
  "tar": "archive",
  "gz": "archive",
  "epub": "ebook",
  "mobi": "ebook",
  "azw3": "ebook",
  "fig": "code",
  "sketch": "code",
  "xd": "code",
  "js": "code",
  "ts": "code",
  "tsx": "code",
  "jsx": "code",
  "py": "code",
  "go": "code",
  "rs": "code",
  "java": "code",
  "rb": "code",
  "sh": "code",
  "json": "code",
  "html": "code",
  "css": "code",
  "txt": "text",
  "md": "text",
  "log": "text"
};

/** Quota thresholds, as percentages. */
export const THRESHOLDS = {"warn":70,"critical":90} as const;

export type QuotaState = "ok" | "warn" | "critical";

/** The one copy of the rule that used to be written out four times. */
export function quotaState(percent: number): QuotaState {
  if (percent > THRESHOLDS.critical) return "critical";
  if (percent > THRESHOLDS.warn) return "warn";
  return "ok";
}

export type ActivityTone = "created" | "read" | "mutated" | "shared" | "neutral" | "destroyed";

/** Action code to tone. Web and desktop render the same feed and must agree. */
export const ACTIVITY_TONE: Record<string, ActivityTone> = {
  "comment_added": "created",
  "comment_deleted": "destroyed",
  "comment_edited": "mutated",
  "dmca_reported": "destroyed",
  "favourite_added": "created",
  "favourite_removed": "destroyed",
  "file_copied": "neutral",
  "file_deleted": "destroyed",
  "file_downloaded": "read",
  "file_hidden": "mutated",
  "file_locked": "mutated",
  "file_moved": "mutated",
  "file_permanently_deleted": "destroyed",
  "file_renamed": "mutated",
  "file_request_created": "read",
  "file_request_revoked": "destroyed",
  "file_request_uploaded": "created",
  "file_restored": "read",
  "file_shared": "shared",
  "file_shared_email": "shared",
  "file_unhidden": "created",
  "file_unlocked": "created",
  "file_uploaded": "created",
  "file_version_uploaded": "created",
  "files_batch_deleted": "destroyed",
  "folder_created": "created",
  "folder_deleted": "destroyed",
  "folder_hidden": "mutated",
  "folder_locked": "mutated",
  "folder_moved": "mutated",
  "folder_renamed": "mutated",
  "folder_shared": "shared",
  "folder_unhidden": "created",
  "folder_unlocked": "created",
  "group_created": "created",
  "group_deleted": "destroyed",
  "group_item_added": "created",
  "group_item_removed": "destroyed",
  "group_updated": "mutated",
  "invite_revoked": "destroyed",
  "link_revoked": "destroyed",
  "member_anchor_updated": "mutated",
  "member_invited": "mutated",
  "member_joined": "created",
  "member_left": "destroyed",
  "member_removed": "destroyed",
  "member_role_changed": "mutated",
  "ownership_transferred": "mutated",
  "plan_changed": "mutated",
  "profile_updated": "mutated",
  "role_created": "created",
  "role_deleted": "destroyed",
  "role_updated": "mutated",
  "share_link_unlocked": "shared",
  "sync_session_completed": "created",
  "sync_session_failed": "destroyed",
  "sync_session_started": "read",
  "workspace_created": "created",
  "workspace_settings_changed": "mutated",
  "workspace_updated": "mutated"
};

const ACTIVITY_COLOR: Record<ActivityTone, { light: string; dark: string }> = {
  "created": {
    "light": "#15803d",
    "dark": "#4ade80"
  },
  "read": {
    "light": "#1d4ed8",
    "dark": "#60a5fa"
  },
  "mutated": {
    "light": "#c2410c",
    "dark": "#fb923c"
  },
  "shared": {
    "light": "#6d28d9",
    "dark": "#c084fc"
  },
  "neutral": {
    "light": "#3f3f46",
    "dark": "#a1a1aa"
  },
  "destroyed": {
    "light": "#d42121",
    "dark": "#f87171"
  }
};

/** The dot colour for an activity row. Unknown codes are neutral, never invisible. */
export function activityColor(action: string, scheme: "light" | "dark" = "light"): string {
  return ACTIVITY_COLOR[ACTIVITY_TONE[action] ?? "neutral"][scheme];
}

/**
 * Every colour a picker has ever offered. `workspaces.icon_color` and
 * `folder_groups.color` are free-form TEXT with no validation, so the database already
 * holds all of these. Nothing is migrated - a stored hex still renders as itself. This
 * lets a picker show which swatch is the current one for a row created before the
 * palettes were unified.
 */
const LEGACY_SWATCH: Record<string, SwatchName> = {
  "#22c55e": "green",
  "#059669": "green",
  "#16a34a": "green",
  "#14b8a6": "teal",
  "#06b6d4": "teal",
  "#0f766e": "teal",
  "#2563eb": "blue",
  "#3b82f6": "blue",
  "#1d4ed8": "blue",
  "#6366f1": "blue",
  "#7c3aed": "violet",
  "#8b5cf6": "violet",
  "#6d28d9": "violet",
  "#db2777": "pink",
  "#ec4899": "pink",
  "#be185d": "pink",
  "#ea580c": "orange",
  "#f97316": "orange",
  "#f59e0b": "orange",
  "#d97706": "orange",
  "#c2410c": "orange",
  "#b45309": "orange",
  "#ef4444": "orange",
  "#1a1917": "graphite",
  "#706e69": "graphite",
  "#4d7c0f": "green"
};

/** The swatch a stored colour belongs to, or null if it was never one of ours. */
export function resolveSwatch(storedHex: string | null | undefined): SwatchName | null {
  if (typeof storedHex !== "string") return null;
  const key = storedHex.trim().toLowerCase();
  if (LEGACY_SWATCH[key]) return LEGACY_SWATCH[key];
  const direct = SWATCHES.find((s) => s.light.toLowerCase() === key || s.dark.toLowerCase() === key);
  return direct ? direct.name : null;
}

/** The fill a stored colour should render as, falling back to the value itself. */
export function swatchFill(storedHex: string | null | undefined, scheme: "light" | "dark"): string {
  const name = resolveSwatch(storedHex);
  if (name) return SWATCH_BY_NAME[name][scheme];
  return typeof storedHex === "string" && storedHex.trim() ? storedHex : SWATCH_BY_NAME.green[scheme];
}

/** A stable default, spread over the set by a hash of the id. */
export function defaultSwatch(id: string): Swatch {
  let hash = 0;
  for (let i = 0; i < String(id).length; i++) hash = (hash * 31 + String(id).charCodeAt(i)) >>> 0;
  return SWATCHES[hash % SWATCHES.length];
}
