import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

/**
 * Inlines the ebook reader into one self-contained HTML string, mirroring
 * apps/mobile/scripts/build-reader.mjs. The reader page itself is shared with
 * mobile: same foliate-js engine, same message protocol, so the desktop app
 * inherits pagination, themes, the TOC and search rather than reimplementing
 * them.
 *
 * The page runs in an iframe here rather than a react-native-webview; the host
 * bridge is shimmed in index.html.
 */
const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const result = await build({
  entryPoints: [join(root, "src/renderer/lib/reader/reader-page/main.js")],
  bundle: true,
  format: "iife",
  target: "es2020",
  minify: true,
  write: false,
  // vendor/foliate-js/pdf.js imports ./vendor/pdfjs/pdf.mjs, which is not
  // vendored: it needs ~13MB of fonts and cmaps and a Worker loaded from a real
  // URL, none of which survives being inlined into one string. view.js only
  // reaches it for PDFs, and this app renders those natively in its own viewer.
  external: ["./pdf.js"],
});

const js = result.outputFiles[0]?.text ?? "";
if (!js || js.trim().length === 0) {
  console.error("build-reader: esbuild produced an empty bundle - refusing to write a stub READER_HTML.");
  process.exit(1);
}

const template = readFileSync(join(root, "src/renderer/lib/reader/reader-page/index.html"), "utf8");
const html = template.replace(
  "<!--INJECT:BUNDLE-->",
  () => `<script>${js.replace(/<\/script>/gi, "<\\/script>")}</script>`,
);

// replace() returns the input unchanged when the marker is missing, which would
// write a "successful" READER_HTML with no reader in it. Fail instead.
if (html === template || html.includes("<!--INJECT:BUNDLE-->") || !html.includes("<script>")) {
  console.error("build-reader: failed to inject the bundle - <!--INJECT:BUNDLE--> marker not found/replaced.");
  process.exit(1);
}

const out = `// GENERATED by scripts/build-reader.mjs - do not edit. Rebuild: npm run build:reader
// eslint-disable
export const READER_HTML = ${JSON.stringify(html)};
`;
writeFileSync(join(root, "src/renderer/lib/reader/readerHtml.generated.ts"), out);
console.log(`readerHtml.generated.ts written (${(html.length / 1024).toFixed(0)} KB)`);
